# name of your github action
name: CI
# this will help you specify where to run
on:
  push:
    branches:
      # this will run on the master branch
      - master
# this is where the magic happens, each job happens in parallel btw
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: actions/setup-node@master
        with:
          node-version: 10.16
      - name: see directory
        run: ls
      - name: Install dependencies
        run: npm install
      - name: Build Electron
        run:  npm run electron:mac
      - name: see directory
        run: ls
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
